### PR TITLE
add missing types of removeRow and removeColumn

### PR DESCRIPTION
**Pull request by MH4GF**

### CODE REVIEW

**Comment by MH4GF** [comment]
Hi @ocavue ,
I have imported the latest master branch and would like you to review it.

**Comment by ocavue** [comment]
As far as I can see, although these two functions are exported in `index.js`, they are designed as private APIs. Is there any reason you have to use these two APIs instead of `deleteRow` and `deleteColumn`, which are public APIs?

**Comment by MH4GF** [comment]
@ocavue thank you for quick response.
In this use case, we wanted to control the cursor position after deletion, which is why the command was unwieldy.
This is because chaining as a transaction is more straightforward to implement than executing multiple commands.

**Comment by ocavue** [comment]
I believe there is some room to make the API have better flexibility. However, for semver compatibility reasons, I will be more cautious about adding public APIs. Although I am one of the maintainers now, my understanding of the code base is still limited. I will keep this PR open, and don't make any decisions for now.

**Comment by ocavue** [comment]
I will closing this for now since we have new native TS support.

**Pull request closed without merging**
