### PR TITLE
Update prosemirror dependencies to typescript version.

### PR DESCRIPTION
**Pull request by zunsthy**

### CODE REVIEW

**Comment by lpellegr** [comment]
This PR works great. I have published a quick package for use from Github packages until this issue is fixed:

https://github.com/noticeable-app/prosemirror-tables/packages/1461458

**Comment by zunsthy** [comment]
I published temporary package for the prosemirror ts update.
https://www.npmjs.com/package/prosemirror-tables-ts

**Comment by lpellegr** [comment]
@RatoX kindly ping

**Comment by whawker** [comment]
@lpellegr any chance your could publish your package on NPM, rather than GitHub packages?

**Comment by lpellegr** [comment]
@whawker I prefer to avoid publishing on NPM since public packages remain forever and the package is only a temporary fix. If you need to use NPM, I suggest trying with the one provided by zunsthy.

**Comment by ocavue** [comment]
Released as v1.2.1. Thanks.

**Pull request closed without merging**
