### PR TITLE
Improve ESM support

### PR DESCRIPTION
**Pull request by lpellegr**
This repository is versioning the file `package-lock.json`. For consistency with other submodules, I have removed it. If you prefer to keep it, the file should be regenerated once other submodules have been released.

### CODE REVIEW

**Comment by lpellegr** [comment]
@RatoX @marduke182 A similar change has been applied to all ProseMirror submodules to improve ESM support (with the exception of this submodule). Is there any chance to get this small change reviewed?

**Comment by marduke182** [comment]
@eshvedai @RatoX let's take a look to this on Monday.

@lpellegr thanks for the contribution.

**Comment by lpellegr** [comment]
Any update?

**Comment by marduke182** [comment]
Yeap, this week has been a bit busy, but we are aware of this. My current concern is:

We are having issues with the latest `prosemirror` modules related to this change. Short story, ESM build is working perfect, but our CJS builds are getting ES6 code.

To prevent this, I would love to do 2 builds one fully transpile to old javascript compatible code `dist/cjs` and a second one with support to ESM `dist/esm`, and use `package.json` to use the respective build.

```json
{
  main: './dist/cjs/index.js'
  modules: './dist/esm/index.js'
}
```

In addition, I would add a ES5 check on the `cjs` build to validate that doesn`t contain any new syntax (const, let, class, etc.).

**Pull request closed without merging**
