### PR TITLE
handleDecorations to check whether table is undefined or null

### PR DESCRIPTION
**Pull request by ianmcateer**
this is to address the issue raised here: https://github.com/ProseMirror/prosemirror-tables/issues/141

1. With column resizing enabled, highlight two or more cells.
2. Without releasing your left mouse button and while your cursor is close enough to a column border to trigger a resize cursor, press the Delete key to delete the cells, alternatively press ctrl + z to undo history if the keymap is enabled

Observe the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at computeMap (index.es.js:273)
    at Function.get (index.es.js:268)
    at handleDecorations (index.es.js:3074)
    at Plugin.decorations (index.es.js:2811)
    at eval (index.es.js:6526)
    at EditorView.someProp (index.es.js:6806)
    at viewDecorations (index.es.js:6525)
    at EditorView.updateStateInner (index.es.js:6682)
    at EditorView.updateState (index.es.js:6652)
    at Editor.dispatchTransaction (tiptap.esm.js:1176)
```
This is because pluginState.activeHandle is not being cleared/reset to -1 when its corresponding node is removed. Also because handleDecorations in columnresizing.js is not checking that table is not null/undefined before passing it to TableMap.get(table).

https://user-images.githubusercontent.com/20038218/168937424-e64c86a2-820b-4582-ae26-756610967787.mp4

### CODE REVIEW

**Comment by ianmcateer** [comment]
@torifat any chance you could take a look at this please?

**Comment by torifat** [comment]
Hi @ianmcateer, the change LGTM. Is it possible to add a test for the change?

**Comment by ianmcateer** [comment]
> Hi @ianmcateer, the change LGTM. Is it possible to add a test for the change?

ty @torifat for getting back- so i've been trying to add a test for the handleDecorations function but it looks like the current test files are in commonJS and are only importing/testing functions/classes from the dist folder, so those methods that are distributed/exported by the package. handleDecorations isnt avilable in /dist so when i try to import the it in the test file i see this

```
import {handleDecorations} from("../src/columnresizing")
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

any guidance here? 🙏

**Comment by RatoX** [comment]
Hey @ianmcateer 

I am working to migrate this repository to use TypeScript soon [read more](https://discuss.prosemirror.net/t/prosemirror-is-now-a-typescript-project/4624/9). Could you rebase your branch and fix this pr?

Btw, you should be able to import the code using ESM now.

**Comment by ianmcateer** [comment]
@RatoX sorry for the late response, i've added a simple test case if you could have a look over? thanks, importing using ESM works fine now

**Pull request merged**
